<?php
include_once '../src/example.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-14 at 00:19:20.
 */
class exampleTest extends PHPUnit_Framework_TestCase {

    /**
     * @var example
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new example;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers example::dodaj
     * @todo   Implement testDodaj().
     */
    public function testDodaj() {
        $wynik = $this->object->dodaj(2, 2);
        $this->assertEquals($wynik, 4);
    }

}
